<%@ page import="org.transitclock.reports.ReportsConfig" %>
<div class="row"
<%
if(!ReportsConfig.isShowPredictionSource()) {
	out.print("style=\"display:none;\""); 
}
%>
>
	<label class="col-sm-12 col-form-label">Prediction Source</label>
	<div class="col-sm-12">
		<select id="predictionSource" name="predictionSource"
				class="form-select"
				title="Specifies which prediction system to display data for. Selecting
					'TransitClock' means will only show prediction data generated by TransitClock.
					If there is another prediction source then can select 'Other'. And selecting 'All'
					displays data for all prediction sources.">
			<option value="TransitClock">TransitClock</option>
			<option value="GTFS-RT (Arrival)">GTFS-RT (Arrival)</option>
			<option value="GTFS-RT (Departure)">GTFS-RT (Departure)</option>
			<option value="GTFS-RT 2nd (Arrival)">GTFS-RT 2nd (Arrival)</option>
			<option value="GTFS-RT 2nd (Departure)">GTFS-RT 2nd (Departure)</option>
			<option value="Other">Other</option>
			<option value="All">All</option>
		</select>

		<span class="select2-selection__arrow"><b role="presentation"></b></span>
	</div>
</div>